### PR TITLE
Us 118

### PR DESCRIPTION
**Pull request by jsmit106**

### CODE REVIEW

**Comment by sjscott9** [comment]
The log button remains enabled when the timer is running, and pressing it will stop the timer without resetting the clock. I will fix the problem by disabling the log button unless the timer is stopped and has a value greater than 00:00:00.

**Comment by sjscott9** [comment]
The timer button appears correctly (only when a Task is highlighted), and the TimerDialog shows the appropriate information. Buttons work and visually update as expected. Ability to log times under the selected task is functional. I vote to merge.

**Comment by mmehan1** [comment]
code looks good, timer works well, ability to log time when resetting or closing works as expected. I vote to merge.

**Comment by jsmit106** [comment]
Verified in formal review everything is good and works as expected. Approve merge.

**Comment by sjscott9** [comment]
Verified in formal review. Vote to merge.

**Pull request merged**
