### PR TITLE
Us 1

### PR DESCRIPTION
**Pull request by jsmit106**

### CODE REVIEW

**Comment by jsmit106** [comment]
Verified templates functioning as expected. Tested templates with no end dates, no description, no type, and no effort (0 by default) in different combinations. I'm good with merging.

**Comment by mmehan1** [comment]
It's a fairly large merge, should we do a formal code review? I can stay after class tomorrow.

**Comment by sjscott9** [comment]
I think a formal review might be more appropriate for our log time and search user stories, since we will all have a part in it. I am fine with merging as all tests pass and the system works as expected.

**Comment by jsmit106** [comment]
A formal review would be a good idea, but I don't think it's necessary. I would be available later in the afternoon tomorrow over Hangouts, but I probably can't do right after class.

**Comment by mmehan1** [comment]
ok scrum master, merge it. we'll do formal reviews on other stories.

**Pull request merged**
